// ============================================================================
// Seismic Anchorage Calculator — Equipment Database
// Code Standards: ASCE 7-22 Chapter 13 + ACI 318-19 Chapter 17
// ============================================================================

import type { EquipmentSpec } from './types.ts';

// ============================================================================
// Equipment Database
// ============================================================================

export const EQUIPMENT_DATABASE: EquipmentSpec[] = [
  // --------------------------------------------------------------------------
  // Trane Precedent RTU — TZK Series (Cooling Only)
  // Ref: Trane Precedent catalog RT-PRC117B-EN
  // All vibration-isolated: componentType "Rooftop unit (RTU) - vibration-isolated"
  // CAR_atGrade=1.8, CAR_aboveGrade=2.2, Rpo=1.3, Omega0p=1.75
  // --------------------------------------------------------------------------
  {
    id: 'trane-tzk048',
    manufacturer: 'Trane',
    series: 'Precedent',
    model: 'TZK048',
    category: 'HVAC',
    type: 'Rooftop Unit (RTU)',
    capacity: '4 ton',
    weight_lbs: 797,
    length_in: 88,
    width_in: 51,
    height_in: 48,
    cg_height_in: 20,
    anchor_spacing_x_in: 41,
    anchor_spacing_y_in: 25,
    CAR_atGrade: 1.8,
    CAR_aboveGrade: 2.2,
    Rpo: 1.3,
    Omega0p: 1.75,
    componentType: 'Rooftop unit (RTU) - vibration-isolated',
    notes: 'Trane Precedent catalog RT-PRC117B-EN',
  },
  {
    id: 'trane-tzk060',
    manufacturer: 'Trane',
    series: 'Precedent',
    model: 'TZK060',
    category: 'HVAC',
    type: 'Rooftop Unit (RTU)',
    capacity: '5 ton',
    weight_lbs: 805,
    length_in: 88,
    width_in: 51,
    height_in: 48,
    cg_height_in: 20,
    anchor_spacing_x_in: 41,
    anchor_spacing_y_in: 25,
    CAR_atGrade: 1.8,
    CAR_aboveGrade: 2.2,
    Rpo: 1.3,
    Omega0p: 1.75,
    componentType: 'Rooftop unit (RTU) - vibration-isolated',
    notes: 'Trane Precedent catalog RT-PRC117B-EN',
  },
  {
    id: 'trane-tzk072',
    manufacturer: 'Trane',
    series: 'Precedent',
    model: 'TZK072',
    category: 'HVAC',
    type: 'Rooftop Unit (RTU)',
    capacity: '6 ton',
    weight_lbs: 810,
    length_in: 88,
    width_in: 51,
    height_in: 48,
    cg_height_in: 20,
    anchor_spacing_x_in: 41,
    anchor_spacing_y_in: 25,
    CAR_atGrade: 1.8,
    CAR_aboveGrade: 2.2,
    Rpo: 1.3,
    Omega0p: 1.75,
    componentType: 'Rooftop unit (RTU) - vibration-isolated',
    notes: 'Trane Precedent catalog RT-PRC117B-EN',
  },
  {
    id: 'trane-tzk090',
    manufacturer: 'Trane',
    series: 'Precedent',
    model: 'TZK090',
    category: 'HVAC',
    type: 'Rooftop Unit (RTU)',
    capacity: '7.5 ton',
    weight_lbs: 859,
    length_in: 104,
    width_in: 51,
    height_in: 48,
    cg_height_in: 21,
    anchor_spacing_x_in: 57,
    anchor_spacing_y_in: 25,
    CAR_atGrade: 1.8,
    CAR_aboveGrade: 2.2,
    Rpo: 1.3,
    Omega0p: 1.75,
    componentType: 'Rooftop unit (RTU) - vibration-isolated',
    notes: 'Trane Precedent catalog RT-PRC117B-EN',
  },
  {
    id: 'trane-tzk102',
    manufacturer: 'Trane',
    series: 'Precedent',
    model: 'TZK102',
    category: 'HVAC',
    type: 'Rooftop Unit (RTU)',
    capacity: '8.5 ton',
    weight_lbs: 875,
    length_in: 104,
    width_in: 51,
    height_in: 48,
    cg_height_in: 21,
    anchor_spacing_x_in: 57,
    anchor_spacing_y_in: 25,
    CAR_atGrade: 1.8,
    CAR_aboveGrade: 2.2,
    Rpo: 1.3,
    Omega0p: 1.75,
    componentType: 'Rooftop unit (RTU) - vibration-isolated',
    notes: 'Trane Precedent catalog RT-PRC117B-EN',
  },
  {
    id: 'trane-tzk120',
    manufacturer: 'Trane',
    series: 'Precedent',
    model: 'TZK120',
    category: 'HVAC',
    type: 'Rooftop Unit (RTU)',
    capacity: '10 ton',
    weight_lbs: 1245,
    length_in: 120,
    width_in: 53,
    height_in: 54,
    cg_height_in: 24,
    anchor_spacing_x_in: 73,
    anchor_spacing_y_in: 27,
    CAR_atGrade: 1.8,
    CAR_aboveGrade: 2.2,
    Rpo: 1.3,
    Omega0p: 1.75,
    componentType: 'Rooftop unit (RTU) - vibration-isolated',
    notes: 'Trane Precedent catalog RT-PRC117B-EN',
  },
  {
    id: 'trane-tzk150',
    manufacturer: 'Trane',
    series: 'Precedent',
    model: 'TZK150',
    category: 'HVAC',
    type: 'Rooftop Unit (RTU)',
    capacity: '12.5 ton',
    weight_lbs: 1285,
    length_in: 120,
    width_in: 53,
    height_in: 54,
    cg_height_in: 24,
    anchor_spacing_x_in: 73,
    anchor_spacing_y_in: 27,
    CAR_atGrade: 1.8,
    CAR_aboveGrade: 2.2,
    Rpo: 1.3,
    Omega0p: 1.75,
    componentType: 'Rooftop unit (RTU) - vibration-isolated',
    notes: 'Trane Precedent catalog RT-PRC117B-EN',
  },
  {
    id: 'trane-tzk180',
    manufacturer: 'Trane',
    series: 'Precedent',
    model: 'TZK180',
    category: 'HVAC',
    type: 'Rooftop Unit (RTU)',
    capacity: '15 ton',
    weight_lbs: 1480,
    length_in: 147,
    width_in: 53,
    height_in: 54,
    cg_height_in: 24,
    anchor_spacing_x_in: 100,
    anchor_spacing_y_in: 27,
    CAR_atGrade: 1.8,
    CAR_aboveGrade: 2.2,
    Rpo: 1.3,
    Omega0p: 1.75,
    componentType: 'Rooftop unit (RTU) - vibration-isolated',
    notes: 'Trane Precedent catalog RT-PRC117B-EN',
  },
  {
    id: 'trane-tzk210',
    manufacturer: 'Trane',
    series: 'Precedent',
    model: 'TZK210',
    category: 'HVAC',
    type: 'Rooftop Unit (RTU)',
    capacity: '17.5 ton',
    weight_lbs: 1560,
    length_in: 147,
    width_in: 53,
    height_in: 54,
    cg_height_in: 24,
    anchor_spacing_x_in: 100,
    anchor_spacing_y_in: 27,
    CAR_atGrade: 1.8,
    CAR_aboveGrade: 2.2,
    Rpo: 1.3,
    Omega0p: 1.75,
    componentType: 'Rooftop unit (RTU) - vibration-isolated',
    notes: 'Trane Precedent catalog RT-PRC117B-EN',
  },
  {
    id: 'trane-tzk240',
    manufacturer: 'Trane',
    series: 'Precedent',
    model: 'TZK240',
    category: 'HVAC',
    type: 'Rooftop Unit (RTU)',
    capacity: '20 ton',
    weight_lbs: 1690,
    length_in: 147,
    width_in: 53,
    height_in: 54,
    cg_height_in: 24,
    anchor_spacing_x_in: 100,
    anchor_spacing_y_in: 27,
    CAR_atGrade: 1.8,
    CAR_aboveGrade: 2.2,
    Rpo: 1.3,
    Omega0p: 1.75,
    componentType: 'Rooftop unit (RTU) - vibration-isolated',
    notes: 'Trane Precedent catalog RT-PRC117B-EN',
  },
  {
    id: 'trane-tzk300',
    manufacturer: 'Trane',
    series: 'Precedent',
    model: 'TZK300',
    category: 'HVAC',
    type: 'Rooftop Unit (RTU)',
    capacity: '25 ton',
    weight_lbs: 2100,
    length_in: 165,
    width_in: 65,
    height_in: 60,
    cg_height_in: 27,
    anchor_spacing_x_in: 118,
    anchor_spacing_y_in: 39,
    CAR_atGrade: 1.8,
    CAR_aboveGrade: 2.2,
    Rpo: 1.3,
    Omega0p: 1.75,
    componentType: 'Rooftop unit (RTU) - vibration-isolated',
    notes: 'Trane Precedent catalog RT-PRC117B-EN',
  },

  // --------------------------------------------------------------------------
  // Trane Precedent RTU — YZK Series (Heat Pump)
  // Ref: Trane Precedent catalog RT-PRC117B-EN
  // --------------------------------------------------------------------------
  {
    id: 'trane-yzk048',
    manufacturer: 'Trane',
    series: 'Precedent',
    model: 'YZK048',
    category: 'HVAC',
    type: 'Rooftop Unit (RTU)',
    capacity: '4 ton',
    weight_lbs: 820,
    length_in: 88,
    width_in: 51,
    height_in: 48,
    cg_height_in: 20,
    anchor_spacing_x_in: 41,
    anchor_spacing_y_in: 25,
    CAR_atGrade: 1.8,
    CAR_aboveGrade: 2.2,
    Rpo: 1.3,
    Omega0p: 1.75,
    componentType: 'Rooftop unit (RTU) - vibration-isolated',
    notes: 'Trane Precedent catalog RT-PRC117B-EN',
  },
  {
    id: 'trane-yzk060',
    manufacturer: 'Trane',
    series: 'Precedent',
    model: 'YZK060',
    category: 'HVAC',
    type: 'Rooftop Unit (RTU)',
    capacity: '5 ton',
    weight_lbs: 830,
    length_in: 88,
    width_in: 51,
    height_in: 48,
    cg_height_in: 20,
    anchor_spacing_x_in: 41,
    anchor_spacing_y_in: 25,
    CAR_atGrade: 1.8,
    CAR_aboveGrade: 2.2,
    Rpo: 1.3,
    Omega0p: 1.75,
    componentType: 'Rooftop unit (RTU) - vibration-isolated',
    notes: 'Trane Precedent catalog RT-PRC117B-EN',
  },
  {
    id: 'trane-yzk072',
    manufacturer: 'Trane',
    series: 'Precedent',
    model: 'YZK072',
    category: 'HVAC',
    type: 'Rooftop Unit (RTU)',
    capacity: '6 ton',
    weight_lbs: 838,
    length_in: 88,
    width_in: 51,
    height_in: 48,
    cg_height_in: 20,
    anchor_spacing_x_in: 41,
    anchor_spacing_y_in: 25,
    CAR_atGrade: 1.8,
    CAR_aboveGrade: 2.2,
    Rpo: 1.3,
    Omega0p: 1.75,
    componentType: 'Rooftop unit (RTU) - vibration-isolated',
    notes: 'Trane Precedent catalog RT-PRC117B-EN',
  },
  {
    id: 'trane-yzk090',
    manufacturer: 'Trane',
    series: 'Precedent',
    model: 'YZK090',
    category: 'HVAC',
    type: 'Rooftop Unit (RTU)',
    capacity: '7.5 ton',
    weight_lbs: 885,
    length_in: 104,
    width_in: 51,
    height_in: 48,
    cg_height_in: 21,
    anchor_spacing_x_in: 57,
    anchor_spacing_y_in: 25,
    CAR_atGrade: 1.8,
    CAR_aboveGrade: 2.2,
    Rpo: 1.3,
    Omega0p: 1.75,
    componentType: 'Rooftop unit (RTU) - vibration-isolated',
    notes: 'Trane Precedent catalog RT-PRC117B-EN',
  },
  {
    id: 'trane-yzk102',
    manufacturer: 'Trane',
    series: 'Precedent',
    model: 'YZK102',
    category: 'HVAC',
    type: 'Rooftop Unit (RTU)',
    capacity: '8.5 ton',
    weight_lbs: 900,
    length_in: 104,
    width_in: 51,
    height_in: 48,
    cg_height_in: 21,
    anchor_spacing_x_in: 57,
    anchor_spacing_y_in: 25,
    CAR_atGrade: 1.8,
    CAR_aboveGrade: 2.2,
    Rpo: 1.3,
    Omega0p: 1.75,
    componentType: 'Rooftop unit (RTU) - vibration-isolated',
    notes: 'Trane Precedent catalog RT-PRC117B-EN',
  },
  {
    id: 'trane-yzk120',
    manufacturer: 'Trane',
    series: 'Precedent',
    model: 'YZK120',
    category: 'HVAC',
    type: 'Rooftop Unit (RTU)',
    capacity: '10 ton',
    weight_lbs: 1245,
    length_in: 120,
    width_in: 53,
    height_in: 54,
    cg_height_in: 24,
    anchor_spacing_x_in: 73,
    anchor_spacing_y_in: 27,
    CAR_atGrade: 1.8,
    CAR_aboveGrade: 2.2,
    Rpo: 1.3,
    Omega0p: 1.75,
    componentType: 'Rooftop unit (RTU) - vibration-isolated',
    notes: 'Trane Precedent catalog RT-PRC117B-EN',
  },
  {
    id: 'trane-yzk150',
    manufacturer: 'Trane',
    series: 'Precedent',
    model: 'YZK150',
    category: 'HVAC',
    type: 'Rooftop Unit (RTU)',
    capacity: '12.5 ton',
    weight_lbs: 1295,
    length_in: 120,
    width_in: 53,
    height_in: 54,
    cg_height_in: 24,
    anchor_spacing_x_in: 73,
    anchor_spacing_y_in: 27,
    CAR_atGrade: 1.8,
    CAR_aboveGrade: 2.2,
    Rpo: 1.3,
    Omega0p: 1.75,
    componentType: 'Rooftop unit (RTU) - vibration-isolated',
    notes: 'Trane Precedent catalog RT-PRC117B-EN',
  },
  {
    id: 'trane-yzk180',
    manufacturer: 'Trane',
    series: 'Precedent',
    model: 'YZK180',
    category: 'HVAC',
    type: 'Rooftop Unit (RTU)',
    capacity: '15 ton',
    weight_lbs: 1510,
    length_in: 147,
    width_in: 53,
    height_in: 54,
    cg_height_in: 24,
    anchor_spacing_x_in: 100,
    anchor_spacing_y_in: 27,
    CAR_atGrade: 1.8,
    CAR_aboveGrade: 2.2,
    Rpo: 1.3,
    Omega0p: 1.75,
    componentType: 'Rooftop unit (RTU) - vibration-isolated',
    notes: 'Trane Precedent catalog RT-PRC117B-EN',
  },
  {
    id: 'trane-yzk210',
    manufacturer: 'Trane',
    series: 'Precedent',
    model: 'YZK210',
    category: 'HVAC',
    type: 'Rooftop Unit (RTU)',
    capacity: '17.5 ton',
    weight_lbs: 1590,
    length_in: 147,
    width_in: 53,
    height_in: 54,
    cg_height_in: 24,
    anchor_spacing_x_in: 100,
    anchor_spacing_y_in: 27,
    CAR_atGrade: 1.8,
    CAR_aboveGrade: 2.2,
    Rpo: 1.3,
    Omega0p: 1.75,
    componentType: 'Rooftop unit (RTU) - vibration-isolated',
    notes: 'Trane Precedent catalog RT-PRC117B-EN',
  },
  {
    id: 'trane-yzk240',
    manufacturer: 'Trane',
    series: 'Precedent',
    model: 'YZK240',
    category: 'HVAC',
    type: 'Rooftop Unit (RTU)',
    capacity: '20 ton',
    weight_lbs: 1720,
    length_in: 147,
    width_in: 53,
    height_in: 54,
    cg_height_in: 24,
    anchor_spacing_x_in: 100,
    anchor_spacing_y_in: 27,
    CAR_atGrade: 1.8,
    CAR_aboveGrade: 2.2,
    Rpo: 1.3,
    Omega0p: 1.75,
    componentType: 'Rooftop unit (RTU) - vibration-isolated',
    notes: 'Trane Precedent catalog RT-PRC117B-EN',
  },
  {
    id: 'trane-yzk300',
    manufacturer: 'Trane',
    series: 'Precedent',
    model: 'YZK300',
    category: 'HVAC',
    type: 'Rooftop Unit (RTU)',
    capacity: '25 ton',
    weight_lbs: 2150,
    length_in: 165,
    width_in: 65,
    height_in: 60,
    cg_height_in: 27,
    anchor_spacing_x_in: 118,
    anchor_spacing_y_in: 39,
    CAR_atGrade: 1.8,
    CAR_aboveGrade: 2.2,
    Rpo: 1.3,
    Omega0p: 1.75,
    componentType: 'Rooftop unit (RTU) - vibration-isolated',
    notes: 'Trane Precedent catalog RT-PRC117B-EN',
  },

  // --------------------------------------------------------------------------
  // Dry-Type Transformers — Generic Typical Values
  // --------------------------------------------------------------------------
  {
    id: 'generic-transformer-75kva',
    manufacturer: 'Generic',
    series: 'Typical',
    model: 'Dry-Type Transformer 75 kVA',
    category: 'Electrical',
    type: 'Dry-Type Transformer',
    capacity: '75 kVA',
    weight_lbs: 450,
    length_in: 30,
    width_in: 18,
    height_in: 36,
    cg_height_in: 18,
    anchor_spacing_x_in: 24,
    anchor_spacing_y_in: 12,
    CAR_atGrade: 1,
    CAR_aboveGrade: 1,
    Rpo: 1.5,
    Omega0p: 2,
    componentType: 'Transformers (dry-type)',
    notes: 'Generic typical values',
  },
  {
    id: 'generic-transformer-150kva',
    manufacturer: 'Generic',
    series: 'Typical',
    model: 'Dry-Type Transformer 150 kVA',
    category: 'Electrical',
    type: 'Dry-Type Transformer',
    capacity: '150 kVA',
    weight_lbs: 650,
    length_in: 34,
    width_in: 20,
    height_in: 42,
    cg_height_in: 21,
    anchor_spacing_x_in: 28,
    anchor_spacing_y_in: 14,
    CAR_atGrade: 1,
    CAR_aboveGrade: 1,
    Rpo: 1.5,
    Omega0p: 2,
    componentType: 'Transformers (dry-type)',
    notes: 'Generic typical values',
  },
  {
    id: 'generic-transformer-225kva',
    manufacturer: 'Generic',
    series: 'Typical',
    model: 'Dry-Type Transformer 225 kVA',
    category: 'Electrical',
    type: 'Dry-Type Transformer',
    capacity: '225 kVA',
    weight_lbs: 850,
    length_in: 38,
    width_in: 22,
    height_in: 48,
    cg_height_in: 24,
    anchor_spacing_x_in: 32,
    anchor_spacing_y_in: 16,
    CAR_atGrade: 1,
    CAR_aboveGrade: 1,
    Rpo: 1.5,
    Omega0p: 2,
    componentType: 'Transformers (dry-type)',
    notes: 'Generic typical values',
  },
  {
    id: 'generic-transformer-300kva',
    manufacturer: 'Generic',
    series: 'Typical',
    model: 'Dry-Type Transformer 300 kVA',
    category: 'Electrical',
    type: 'Dry-Type Transformer',
    capacity: '300 kVA',
    weight_lbs: 1100,
    length_in: 42,
    width_in: 24,
    height_in: 54,
    cg_height_in: 27,
    anchor_spacing_x_in: 36,
    anchor_spacing_y_in: 18,
    CAR_atGrade: 1,
    CAR_aboveGrade: 1,
    Rpo: 1.5,
    Omega0p: 2,
    componentType: 'Transformers (dry-type)',
    notes: 'Generic typical values',
  },
  {
    id: 'generic-transformer-500kva',
    manufacturer: 'Generic',
    series: 'Typical',
    model: 'Dry-Type Transformer 500 kVA',
    category: 'Electrical',
    type: 'Dry-Type Transformer',
    capacity: '500 kVA',
    weight_lbs: 1800,
    length_in: 50,
    width_in: 28,
    height_in: 60,
    cg_height_in: 30,
    anchor_spacing_x_in: 44,
    anchor_spacing_y_in: 22,
    CAR_atGrade: 1,
    CAR_aboveGrade: 1,
    Rpo: 1.5,
    Omega0p: 2,
    componentType: 'Transformers (dry-type)',
    notes: 'Generic typical values',
  },
  {
    id: 'generic-transformer-750kva',
    manufacturer: 'Generic',
    series: 'Typical',
    model: 'Dry-Type Transformer 750 kVA',
    category: 'Electrical',
    type: 'Dry-Type Transformer',
    capacity: '750 kVA',
    weight_lbs: 2800,
    length_in: 58,
    width_in: 32,
    height_in: 66,
    cg_height_in: 33,
    anchor_spacing_x_in: 52,
    anchor_spacing_y_in: 26,
    CAR_atGrade: 1,
    CAR_aboveGrade: 1,
    Rpo: 1.5,
    Omega0p: 2,
    componentType: 'Transformers (dry-type)',
    notes: 'Generic typical values',
  },
  {
    id: 'generic-transformer-1000kva',
    manufacturer: 'Generic',
    series: 'Typical',
    model: 'Dry-Type Transformer 1000 kVA',
    category: 'Electrical',
    type: 'Dry-Type Transformer',
    capacity: '1000 kVA',
    weight_lbs: 4200,
    length_in: 66,
    width_in: 36,
    height_in: 72,
    cg_height_in: 36,
    anchor_spacing_x_in: 60,
    anchor_spacing_y_in: 30,
    CAR_atGrade: 1,
    CAR_aboveGrade: 1,
    Rpo: 1.5,
    Omega0p: 2,
    componentType: 'Transformers (dry-type)',
    notes: 'Generic typical values',
  },

  // --------------------------------------------------------------------------
  // Standby Generators — Generic Typical Values
  // --------------------------------------------------------------------------
  {
    id: 'generic-generator-100kw',
    manufacturer: 'Generic',
    series: 'Typical',
    model: 'Standby Generator 100 kW',
    category: 'Electrical',
    type: 'Standby Generator',
    capacity: '100 kW',
    weight_lbs: 3200,
    length_in: 96,
    width_in: 36,
    height_in: 60,
    cg_height_in: 30,
    anchor_spacing_x_in: 84,
    anchor_spacing_y_in: 30,
    CAR_atGrade: 1,
    CAR_aboveGrade: 1,
    Rpo: 1.5,
    Omega0p: 2,
    componentType: 'Generators',
    notes: 'Generic typical values',
  },
  {
    id: 'generic-generator-200kw',
    manufacturer: 'Generic',
    series: 'Typical',
    model: 'Standby Generator 200 kW',
    category: 'Electrical',
    type: 'Standby Generator',
    capacity: '200 kW',
    weight_lbs: 5500,
    length_in: 120,
    width_in: 42,
    height_in: 66,
    cg_height_in: 33,
    anchor_spacing_x_in: 108,
    anchor_spacing_y_in: 36,
    CAR_atGrade: 1,
    CAR_aboveGrade: 1,
    Rpo: 1.5,
    Omega0p: 2,
    componentType: 'Generators',
    notes: 'Generic typical values',
  },
  {
    id: 'generic-generator-500kw',
    manufacturer: 'Generic',
    series: 'Typical',
    model: 'Standby Generator 500 kW',
    category: 'Electrical',
    type: 'Standby Generator',
    capacity: '500 kW',
    weight_lbs: 12000,
    length_in: 168,
    width_in: 54,
    height_in: 78,
    cg_height_in: 39,
    anchor_spacing_x_in: 156,
    anchor_spacing_y_in: 48,
    CAR_atGrade: 1,
    CAR_aboveGrade: 1,
    Rpo: 1.5,
    Omega0p: 2,
    componentType: 'Generators',
    notes: 'Generic typical values',
  },
  {
    id: 'generic-generator-1000kw',
    manufacturer: 'Generic',
    series: 'Typical',
    model: 'Standby Generator 1000 kW',
    category: 'Electrical',
    type: 'Standby Generator',
    capacity: '1000 kW',
    weight_lbs: 24000,
    length_in: 240,
    width_in: 66,
    height_in: 90,
    cg_height_in: 45,
    anchor_spacing_x_in: 228,
    anchor_spacing_y_in: 60,
    CAR_atGrade: 1,
    CAR_aboveGrade: 1,
    Rpo: 1.5,
    Omega0p: 2,
    componentType: 'Generators',
    notes: 'Generic typical values',
  },
  {
    id: 'generic-generator-2000kw',
    manufacturer: 'Generic',
    series: 'Typical',
    model: 'Standby Generator 2000 kW',
    category: 'Electrical',
    type: 'Standby Generator',
    capacity: '2000 kW',
    weight_lbs: 48000,
    length_in: 336,
    width_in: 84,
    height_in: 108,
    cg_height_in: 54,
    anchor_spacing_x_in: 324,
    anchor_spacing_y_in: 78,
    CAR_atGrade: 1,
    CAR_aboveGrade: 1,
    Rpo: 1.5,
    Omega0p: 2,
    componentType: 'Generators',
    notes: 'Generic typical values',
  },

  // --------------------------------------------------------------------------
  // Chillers — Generic Typical Values
  // --------------------------------------------------------------------------
  {
    id: 'generic-chiller-50ton',
    manufacturer: 'Generic',
    series: 'Typical',
    model: 'Chiller 50 Ton',
    category: 'HVAC',
    type: 'Chiller',
    capacity: '50 ton',
    weight_lbs: 4500,
    length_in: 120,
    width_in: 48,
    height_in: 72,
    cg_height_in: 36,
    anchor_spacing_x_in: 108,
    anchor_spacing_y_in: 42,
    CAR_atGrade: 1,
    CAR_aboveGrade: 1,
    Rpo: 1.5,
    Omega0p: 2,
    componentType: 'Wet-side HVAC (boilers, chillers, cooling towers)',
    notes: 'Generic typical values',
  },
  {
    id: 'generic-chiller-100ton',
    manufacturer: 'Generic',
    series: 'Typical',
    model: 'Chiller 100 Ton',
    category: 'HVAC',
    type: 'Chiller',
    capacity: '100 ton',
    weight_lbs: 8000,
    length_in: 168,
    width_in: 60,
    height_in: 84,
    cg_height_in: 42,
    anchor_spacing_x_in: 156,
    anchor_spacing_y_in: 54,
    CAR_atGrade: 1,
    CAR_aboveGrade: 1,
    Rpo: 1.5,
    Omega0p: 2,
    componentType: 'Wet-side HVAC (boilers, chillers, cooling towers)',
    notes: 'Generic typical values',
  },
  {
    id: 'generic-chiller-200ton',
    manufacturer: 'Generic',
    series: 'Typical',
    model: 'Chiller 200 Ton',
    category: 'HVAC',
    type: 'Chiller',
    capacity: '200 ton',
    weight_lbs: 18000,
    length_in: 240,
    width_in: 72,
    height_in: 96,
    cg_height_in: 48,
    anchor_spacing_x_in: 228,
    anchor_spacing_y_in: 66,
    CAR_atGrade: 1,
    CAR_aboveGrade: 1,
    Rpo: 1.5,
    Omega0p: 2,
    componentType: 'Wet-side HVAC (boilers, chillers, cooling towers)',
    notes: 'Generic typical values',
  },
  {
    id: 'generic-chiller-500ton',
    manufacturer: 'Generic',
    series: 'Typical',
    model: 'Chiller 500 Ton',
    category: 'HVAC',
    type: 'Chiller',
    capacity: '500 ton',
    weight_lbs: 45000,
    length_in: 360,
    width_in: 96,
    height_in: 120,
    cg_height_in: 60,
    anchor_spacing_x_in: 348,
    anchor_spacing_y_in: 90,
    CAR_atGrade: 1,
    CAR_aboveGrade: 1,
    Rpo: 1.5,
    Omega0p: 2,
    componentType: 'Wet-side HVAC (boilers, chillers, cooling towers)',
    notes: 'Generic typical values',
  },
];

// ============================================================================
// Search Function
// ============================================================================

/**
 * Search the equipment database by query string with optional category filter.
 * Searches across model, manufacturer, type, and capacity fields (case-insensitive).
 * Results are sorted by relevance: exact model matches first, then partial matches.
 */
export function searchEquipment(
  query: string,
  category?: string,
): EquipmentSpec[] {
  const q = query.toLowerCase().trim();
  if (!q) return category ? EQUIPMENT_DATABASE.filter((e) => e.category === category) : [...EQUIPMENT_DATABASE];

  const allEquipment = getAllEquipment();

  // Filter by category first if provided
  const pool = category
    ? allEquipment.filter((e) => e.category === category)
    : allEquipment;

  // Score each item for relevance
  const scored = pool
    .map((equipment) => {
      let score = 0;
      const model = equipment.model.toLowerCase();
      const manufacturer = equipment.manufacturer.toLowerCase();
      const type = equipment.type.toLowerCase();
      const capacity = equipment.capacity.toLowerCase();

      // Exact model match — highest priority
      if (model === q) {
        score += 100;
      } else if (model.startsWith(q)) {
        score += 80;
      } else if (model.includes(q)) {
        score += 60;
      }

      // Manufacturer match
      if (manufacturer === q) {
        score += 50;
      } else if (manufacturer.includes(q)) {
        score += 30;
      }

      // Type match
      if (type === q) {
        score += 40;
      } else if (type.includes(q)) {
        score += 20;
      }

      // Capacity match
      if (capacity === q) {
        score += 40;
      } else if (capacity.includes(q)) {
        score += 20;
      }

      return { equipment, score };
    })
    .filter((item) => item.score > 0);

  // Sort by score descending
  scored.sort((a, b) => b.score - a.score);

  return scored.map((item) => item.equipment);
}

// ============================================================================
// Custom Equipment (localStorage)
// ============================================================================

const CUSTOM_EQUIPMENT_KEY = 'custom_equipment';

/**
 * Retrieve custom equipment entries from localStorage.
 */
export function getCustomEquipment(): EquipmentSpec[] {
  if (typeof window === 'undefined') return [];
  try {
    const stored = localStorage.getItem(CUSTOM_EQUIPMENT_KEY);
    if (!stored) return [];
    const parsed = JSON.parse(stored);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

/**
 * Save a custom equipment entry to localStorage.
 * Automatically sets `isCustom: true` on the entry.
 */
export function saveCustomEquipment(equipment: EquipmentSpec): void {
  if (typeof window === 'undefined') return;
  const existing = getCustomEquipment();
  const updated = [...existing, { ...equipment, isCustom: true }];
  localStorage.setItem(CUSTOM_EQUIPMENT_KEY, JSON.stringify(updated));
}

/**
 * Delete a custom equipment entry from localStorage by ID.
 */
export function deleteCustomEquipment(id: string): void {
  if (typeof window === 'undefined') return;
  const existing = getCustomEquipment();
  const updated = existing.filter((e) => e.id !== id);
  localStorage.setItem(CUSTOM_EQUIPMENT_KEY, JSON.stringify(updated));
}

/**
 * Get all equipment: built-in database combined with user's custom entries.
 * Custom equipment is appended after the built-in database.
 */
export function getAllEquipment(): EquipmentSpec[] {
  return [...EQUIPMENT_DATABASE, ...getCustomEquipment()];
}
